{
 "title": "Jaleómetros",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "zones",
    "label": "Zonas",
    "query": "SELECT \"zone\" FROM public.zones;\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Jaleómetros",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n\ts.latitude, \r\n\ts.longitude, \r\n\ts.name AS Name,\r\n\tn.laeq AS LAeq\r\nFROM \r\n\tsensors s\r\nLEFT JOIN (\r\n    SELECT\r\n        device_id,\r\n        laeq,\r\n        ROW_NUMBER() OVER (PARTITION BY device_id ORDER BY id DESC) AS rn\r\n    FROM\r\n        noise\r\n) n ON s.id = n.device_id AND n.rn = 1\r\nWHERE \r\n    s.type_id = 2\r\nORDER BY\r\n    s.latitude;"
    }
   ]
  },
  {
   "title": "Avisos de ruido máximo por zona",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "select count(*) as \"Alarmas\",a.\"zone\" as \"Zona\"\r\nfrom alarms a\r\nWHERE \r\n   $__timeFilter(\"time\" - INTERVAL '1 hour') \r\n\tand\ta.zone in ($zones)\r\n\tand a.\"type\" = 'LA_max'\r\ngroup by a.\"zone\" \r\norder by \"Alarmas\" DESC"
    }
   ]
  },
  { "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 } },
  {
   "title": "Alarmas de exceso de ruido sancionable",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 7 },
   "targets": [
    {
     "rawSql": "select count(*) as \"Alarmas\",a.\"zone\" as \"Zona\"\r\nfrom alarms a\r\nWHERE \r\n   $__timeFilter(\"time\" - INTERVAL '1 hour') \r\n\tand\ta.zone in ($zones)\r\n\tand (a.\"type\" = 'LAeq_Up' or a.\"type\" = 'LAeq_close')\r\ngroup by a.\"zone\" \r\norder by \"Alarmas\" DESC"
    }
   ]
  },
  {
   "title": "Alarmas. LA máximo superado (Sancionable)",
   "type": "status-history",
   "description": "¨Ruido medio\"",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", address_public, measurement AS \".\" FROM alarms \r\nWHERE  \r\n  \"type\" = 'LAeq_Up' \r\nAND $__timeFilter(\"time\" - INTERVAL '1 hour') \r\nAND zone in ($zones) \r\nORDER BY \"time\" ASC "
    }
   ]
  },
  {
   "title": "LAeq",
   "type": "timeseries",
   "description": "LAeq (Equivalent Continuous Sound Pressure Level) nivel sonoro promediado en 10 min\n- Límite diurno: 85 dBa\n- Límite nocturno: 55 dBa",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "rawSql": "select (n.time - INTERVAL '1 hour') as \"time\", '(Id:'||s.id||') '||s.address_public  as \"device\", n.laeq as \"laeq\"\r\nfrom noise n\r\ninner join sensors s on s.id = n.device_id\r\nWHERE $__timeFilter(\"time\" - INTERVAL '1 hour') AND zone in ($zones)\r\nORDER BY \"time\" ASC "
    }
   ]
  },
  {
   "title": "LA máximo",
   "type": "timeseries",
   "description": "LA (dB). Nivel sonoro máximo detectado en un periodo de 10 min.",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "rawSql": "select (n.time - INTERVAL '1 hour') as \"time\", '(Id:'||s.id||') '||s.address_public  as \"device\", n.lamax as \"lamax\"\r\nfrom noise n\r\ninner join sensors s on s.id = n.device_id\r\nWHERE $__timeFilter(\"time\" - INTERVAL '1 hour') AND zone in ($zones)\r\nORDER BY \"time\" ASC "
    }
   ]
  },
  {
   "title": "LA (dB) Nivel sonoro mínimo detectado en un periodo de 10 min.",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "rawSql": "select (n.time - INTERVAL '1 hour') as \"time\", '(Id:'||s.id||') '||s.address_public  as \"device\", n.lamin as \"lamin\"\r\nfrom noise n\r\ninner join sensors s on s.id = n.device_id\r\nWHERE $__timeFilter(\"time\" - INTERVAL '1 hour') AND zone in ($zones)\r\nORDER BY \"time\" ASC "
    }
   ]
  },
  {
   "title": "Alarmas. LA máximo superado ",
   "type": "heatmap",
   "description": "¨Ruido puntual máximo¨ se registra cuando se detecta que ha superado el límite tres veces consecutivas durante los últimos 30 minutos ",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", address_public, measurement AS \".\" FROM alarms WHERE \"type\" = 'LA_max' AND zone in ($zones) ORDER BY \"time\" ASC "
    }
   ]
  }
 ]
}